### ISSUE TITLE
Attributes not applying properly to armor despite being fixed in the latest mod version

### ISSUE THREAD

**Issue by Blob336** [nvb-uy/CIA#1]
[custom_item_attributes.txt](https://github.com/nvb-uy/CIA/files/14120642/custom_item_attributes.txt)

Putting on a diamond helmet, then diamond boots clearly shows the issue. Also taking off one of those after.
The tooltips look fine.

____________________________________________
Minecraft 1.20.1 with Fabric Loader 0.15.6
customitemattributes 1.1.0
fabric-api 0.91.0+1.20.1

**Comment by nvb-uy** [comment]
is the mod present in both client and server with the same config? Send me your logs from both

**Comment by Blob336** [comment]
[latest.log](https://github.com/nvb-uy/CIA/files/14154556/latest.log)
I only tried the mod in singleplayer

**Comment by nvb-uy** [comment]
Can't reproduce
