### ISSUE TITLE
Having trouble changing more than one item

### ISSUE THREAD

**Issue by Jonsuo** [nvb-uy/CIA#11]
Ive been trying to change cataclysm weapons and armor to balance them with other mods but i havent been able to figure out what formatting the config needs, every way ive tried has crashed it.

This is the way ive tried it so far.
[custom_item_attributes.txt](https://github.com/user-attachments/files/16228405/custom_item_attributes.txt)

Could i get the correct formatting for this?
Tyvm 
Nap

**Comment by nvb-uy** [comment]
Fixed on 2.0.0, please read full changelog as the config moved locations and the format also changed.
