### ISSUE TITLE
Add option to fully override attributes (Rather than add attributes)

### ISSUE THREAD

**Issue by yoshisman8** [nvb-uy/CIA#4]
I got this mod hoping i could rebalance some OP armor by changing their vanilla and modded attributes. But ended up a bit disappointed when my new attributes were just merged with the existing ones. Is there some way to actually tell this mod to fully override all item attributes?

**Comment by nvb-uy** [comment]
Not currently

**Comment by nvb-uy** [comment]
Fixed on 2.0.0, please read full changelog as the config moved locations and the format also changed.
