### ISSUE TITLE
Can't seem to find Config

### ISSUE THREAD

**Issue by GenDutchman** [nvb-uy/CIA#5]
Hello all,

Ive added this mod into my server modpack server side only, and its not showing up on the servers config files, even in the world files, is there a specific place that they should be, it seems to be hiding on me.

Thanks heaps
-Gen

**Comment by NotTohm** [comment]
me too, u on 1.20.1 forge?

**Comment by GenDutchman** [comment]
Yes I am on 1.20.2 Forge

**Comment by NotTohm** [comment]
oh do you have sinytra connector and its dependencies? that fixed it for me

**Comment by GenDutchman** [comment]
no i havent, ill give them a go and see if it works, thanks

**Comment by GenDutchman** [comment]
still not showing up when i have them added

**Comment by GenDutchman** [comment]
Where did you find the config, cause its still not showing up, would it bet the normal config or the world config?

**Comment by NotTohm** [comment]
if u havent booted up the game with them do that. its in the normal config tho and if u cant find it now idk what to tell ya

**Comment by nvb-uy** [comment]
Please make sure you have Necronomicon installed.

**Comment by nvb-uy** [comment]
On forge you also need connector, the mod won't work without it.
