### ISSUE TITLE
custom_item_attributes.json5 works on client but not on server

### ISSUE THREAD

**Issue by ninjaeon** [nvb-uy/CIA#6]
Any edits I make to an item in the custom_item_attributes.json5 file on the server side have no effect. However, when I edit the custom_item_attributes.json5 file on the client side, the item reflects the changes made in the client-side version of the file, even while I am connected to the same server with this client.

If I leave the custom_item_attributes.json5 file on the client side unchanged, there is no effect on the item when the custom_item_attributes.json5 file is modified on the server side.

Fabric 1.20.1
CIA-1.1.0-Fabric-MC1.20.1.jar
Necronomicon-Fabric-1.4.2.jar
both mods installed on both client and server

Full Log (Client):
https://mclo.gs/T6kloBM

Full Log (Server):
https://mclo.gs/JgJqfdu

custom_item_attributes.json5 (Server):
https://pastebin.com/ecr13aPt

custom_item_attributes.json5 (Client):
https://pastebin.com/d0LPfE7X

**Comment by nvb-uy** [comment]
It's a desync issue on the tooltip, the attributes still apply but you'll need to add the config to the client to see the changes too.
